[workspace]
authors = ["Daniel Alfonsetti <daniel.alfonsetti@gmail.com>"]
channels = ["conda-forge"]
name = "retirement"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ipykernel = ">=6.30.1,<7"
python = "3.13.*"
numpy = ">=2.3.2,<3"
